name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        registry: registry.antosubash.com
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - uses: actions/checkout@v2
    - name: Build the abpreact nextjs image
      run: docker build ./src --file src/Dockerfile --tag abpreactnextjs:dev
    - name: Docker tag next image
      run: docker tag abpreactnextjs:dev registry.antosubash.com/abpreactnextjs:dev
    - name: Push abpreact-nextjs image
      run: docker push registry.antosubash.com/abpreactnextjs:dev
    - name: Send Http Post Request to Deploy NextJs App
      uses: fjogeleit/http-request-action@v1
      with:
        url: ${{ secrets.NEXTJS_WEBHOOK_URL }}
        method: 'POST'