name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    defaults:
      run:
        working-directory: ./src
    runs-on: ubuntu-latest

    steps:
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        registry: registry.antosubash.com
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - uses: actions/checkout@v3
    - name: Build the abpreact nextjs image
      run: docker build . --file ./apps/abp/Dockerfile --tag abpreactnextjs:turbo
    - name: Docker tag next image
      run: docker tag abpreactnextjs:turbo registry.antosubash.com/abpreactnextjs:turbo
    - name: Push abpreact-nextjs image
      run: docker push registry.antosubash.com/abpreactnextjs:turbo
    # - name: Send Http Post Request to Deploy NextJs App
    #   uses: fjogeleit/http-request-action@v1
    #   with:
    #     url: ${{ secrets.NEXTJS_WEBHOOK_URL }}
    #     method: 'POST'